clone:
  git:
    image: plugins/git

pipeline:
  node6:
    image: node:6
    group: validate
    commands:
    - npm i -g npm
    - npm i
    - npm test
  node7:
    image: node:7
    group: validate
    commands:
    - npm i -g npm
    - npm i
    - npm test
  node8:
    image: node:8
    group: validate
    commands:
    - npm i -g npm
    - npm i
    - npm test
  node9:
    image: node:9
    group: validate
    commands:
    - npm i -g npm
    - npm i
    - npm test
  node10:
    image: node:10
    group: validate
    commands:
    - npm i -g npm
    - npm i
    - npm test
  node11:
    image: node:11
    group: validate
    commands:
    - npm i -g npm
    - npm i
    - npm test
  publish:
    image: node:10
    commands:
      - npm i -g npm
      - echo "//registry.npmjs.org/:_authToken=$${NPM_DEPLOY_TOKEN}" > ~/.npmrc
      - npm publish
    secrets:
      - npm_deploy_token
    when:
      event: tag
      branch:
        - include: [ v* ]