clone:
  git:
    image: plugins/git

pipeline:
  install:
    image: node:21
    commands:
      - npm ci
  test:
    group: test
    image: node:21
    commands:
    - npm test
  publish:
    image: node:21
    commands:
      - echo "//registry.npmjs.org/:_authToken=$${NPM_DEPLOY_TOKEN}" > ~/.npmrc
      - echo "unsafe-perm=true" >> ~/.npmrc
      - npm publish
    secrets:
      - npm_deploy_token
    when:
      event: tag
      branch:
        - include: [ v* ]