language: node_js
install:
  - npm install
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
deploy:
  provider: npm
  email: "terodoxnpm@gmail.com"
  api_key: "${NPM_DEPLOY_TOKEN}"
  on:
    tags: true
    only:
      - /^v\d+\.\d+\.\d+$/